### PR TITLE
Groups and unprotected ACLs support

### PR DESCRIPTION
**Pull request by pashazz**
This pull request adds:

- support for WebDAV groups (as in DAV:group-membership)
- support for unprotected ACEs that are evaluated in the following order:

1. Protected ACEs from a current item - Owner has full access,  everyone else can only do current-user-privilege-set.
2. Protected ACEs from parent items
3. Unprotected ACEs from current item
4. Unprotected ACEs from parent items

Unprotected ACEs are saved in the database alongside their respecitve  **Item**s.

This pull request also adds support for integrational tests using apache http client, see AbstractIntegrationalTest class

This pull request also removes code duplications in SecurityAdvice and UserAclEvaluator

### CODE REVIEW

**Comment by danielgrigore** [comment]
Dear @pashazz  

Thank you for the interest shown in Cosmo Caldav server project.
I briefly had a look on the code included in these two pull requests.
As far as I saw both of them are related to Web DAV protocol.
We want to keep in Cosmo only CalDAV related features. For this reason I will not merge your pull requests in Cosmo.
In the future if you have any CalDAV features/improvements you may want to submit I will be glad to review them.
I also created a [guideline](https://github.com/1and1/cosmo/blob/master/CONTRIBUTING.adoc) for pull requests you may want to read before submitting a new one.

Best regards,

**Comment by pashazz** [comment]
OK, so you don't want groups and unprotected ACLs, that's fine, I'll maintain a separate fork for that.

What about scheduling? https://tools.ietf.org/html/rfc6638 I'm also working on that?

**Comment by danielgrigore** [comment]
Hi @pashazz 

Scheduling is an interesting feature but unfortunately it only covers users of the same system.
For scheduling the best way is using [iMip](https://tools.ietf.org/html/rfc6047) and [iTip](https://tools.ietf.org/html/rfc5546) protocols which applies to users from external systems as well, but these two are beyond Cosmo's purpose.
Cheers,

**Comment by f1-outsourcing** [comment]
> Hi @pashazz @danielgrigore 
> 
> Scheduling is an interesting feature but unfortunately it only covers users of the same system. For scheduling the best way is using [iMip](https://tools.ietf.org/html/rfc6047) and [iTip](https://tools.ietf.org/html/rfc5546) protocols which applies to users from external systems as well, but these two are beyond Cosmo's purpose. Cheers,

I don't really get this "beyond cosmo's purpose", why would scheduling be not be interesting to add? The same is with this group-membership ( I don't really know what this is, I assume you can grant access to your calendar etc)

I would like to maintain a calendar on the phone/desktop that is being published on a website. Is this even possible with cosmo?

**Pull request closed without merging**
